myDjango/demo/urls.py
from django.urls import path
from . import views

app_name = 'demo'
urlpatterns = [
    path('index', views.index, name='index'),
    path('detail/', views.detail, name='detail'),
    path('addBook/', views.add_book, name='addBook'),
    path('delBook/<int:book_id>', views.delete_book, name='delBook'),
    path('editBook/<int:book_id>', views.edit_book, name='editBook'),
]

myDjango/myDjango/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('demo/', include('demo.urls')),
    path('admin/', admin.site.urls),
]

myDjango/demo/models.py
from django.db import models


class Book(models.Model):
    name = models.CharField(max_length=200)
    author = models.CharField(max_length=100)
    pub_house = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

myDjango/demo/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import Book
from django.http import HttpResponseRedirect
from django.urls import reverse


def index(request):
    return HttpResponse("Hello, world!")


def detail(request):
    book_list = Book.objects.order_by('-pub_date')[:5]
    context = {'book_list': book_list}
    return render(request, 'demo/detail.html', context)


def add_book(request):
    if request.method == 'POST':
        temp_name = request.POST['name']
        temp_author = request.POST['author']
        temp_pub_house = request.POST['pub_house']

        from django.utils import timezone
        temp_book = Book(name=temp_name, author=temp_author, pub_house=temp_pub_house, pub_date=timezone.now())
        temp_book.save()
        return HttpResponseRedirect(reverse('demo:detail'))
    return render(request, 'demo/add.html')


def delete_book(request, book_id):
    temp_book_id = book_id
    Book.objects.filter(id=temp_book_id).delete()
    return HttpResponseRedirect(reverse('demo:detail'))


def edit_book(request, book_id):
    temp_book_id = book_id
    book = Book.objects.filter(id=temp_book_id).first()
    context = {'book': book}
    if request.method == 'POST':
        temp_name = request.POST['name']
        temp_author = request.POST['author']
        temp_pub_house = request.POST['pub_house']
        from django.utils import timezone
        Book.objects.filter(id=temp_book_id).update(name=temp_name, author=temp_author,
                                                    pub_house=temp_pub_house, pub_date=timezone.now())
        return HttpResponseRedirect(reverse('demo:detail'))
    return render(request, 'demo/edit.html', context)

myDjango/demo/templates/demo/add.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form action="{% url 'demo:addBook' %}" method="post" name="addBook">
    {% csrf_token %}
    <p><span>书名：</span><input type="text"  name="name"></p>
    <p><span>作者：</span><input type="text"  name="author"></p>
    <p><span>出版社：</span><input type="text"  name="pub_house"></p>
    <input type="submit" value="添加">
</form>
</body>
</html>

myDjango/demo/templates/demo/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>Book List</h1>
<a href="{% url 'demo:addBook' %}" class="btn btn-success" style="margin-right: 75px">添加</a>
<table>
    <tr>
        <td>书名</td>
        <td>作者</td>
        <td>出版社</td>
        <td>出版时间</td>
    </tr>
{% for book in book_list.all %}
    <tr>
        <td>{{ book.name }}</td>
        <td>{{ book.author }}</td>
        <td>{{ book.pub_house }}</td>
        <td>{{ book.pub_date }}</td>
        <td><a href="{% url 'demo:editBook' book.id %}">编辑</a></td>
        <td><a href="{% url 'demo:delBook' book.id %}">删除</a></td>
    </tr>
{% endfor %}
</table>
</body>
</html>

myDjango/demo/templates/demo/edit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form action="{% url 'demo:editBook' book.id %}" method="post" name="editBook">
    {% csrf_token %}
    <p><span>书名：</span><input type="text"  name="name" value="{{ book.name }}"></p>
    <p><span>作者：</span><input type="text"  name="author" value="{{ book.author }}"></p>
    <p><span>出版社：</span><input type="text"  name="pub_house" value="{{ book.pub_house }}"></p>
    <input type="submit" value="修改">
    <td><a href="{% url 'demo:detail' %}">取消</a></td>
</form>
</body>
</html>